apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from base
resources:
  - ../../base

# Prod-specific patches
patches:
  - path: patches/deployment.yaml

# Prod-specific labels
commonLabels:
  environment: prod
