apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: health-service-dashboard
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
    files:
      - health-service.json=dashboards/health-service.json

  - name: nginx-ingress-dashboard
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
    files:
      - nginx-ingress.json=dashboards/nginx-ingress.json
